import "dotenv/config";
import pg from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { techSuggestions } from "./schema.js";

const SUGGESTIONS: { name: string; category: string }[] = [
  // ── Language ────────────────────────────────────────────────────────────────
  { name: "JavaScript",   category: "Language" },
  { name: "TypeScript",   category: "Language" },
  { name: "Python",       category: "Language" },
  { name: "Go",           category: "Language" },
  { name: "Rust",         category: "Language" },
  { name: "Java",         category: "Language" },
  { name: "C#",           category: "Language" },
  { name: "C++",          category: "Language" },
  { name: "C",            category: "Language" },
  { name: "Ruby",         category: "Language" },
  { name: "PHP",          category: "Language" },
  { name: "Swift",        category: "Language" },
  { name: "Kotlin",       category: "Language" },
  { name: "Scala",        category: "Language" },
  { name: "Dart",         category: "Language" },
  { name: "Elixir",       category: "Language" },
  { name: "R",            category: "Language" },
  { name: "Haskell",      category: "Language" },
  { name: "Clojure",      category: "Language" },
  { name: "Lua",          category: "Language" },
  { name: "Shell/Bash",   category: "Language" },
  { name: "SQL",          category: "Language" },
  { name: "HTML/CSS",     category: "Language" },
  { name: "Zig",          category: "Language" },
  { name: "OCaml",        category: "Language" },

  // ── Frontend ───────────────────────────────────────────────────────────────
  { name: "React",             category: "Frontend" },
  { name: "Vue.js",            category: "Frontend" },
  { name: "Angular",           category: "Frontend" },
  { name: "Svelte",            category: "Frontend" },
  { name: "Next.js",           category: "Frontend" },
  { name: "Nuxt.js",           category: "Frontend" },
  { name: "Remix",             category: "Frontend" },
  { name: "Astro",             category: "Frontend" },
  { name: "SvelteKit",         category: "Frontend" },
  { name: "Htmx",              category: "Frontend" },
  { name: "jQuery",            category: "Frontend" },
  { name: "Tailwind CSS",      category: "Frontend" },
  { name: "Bootstrap",         category: "Frontend" },
  { name: "Sass/SCSS",         category: "Frontend" },
  { name: "Styled Components", category: "Frontend" },
  { name: "CSS Modules",       category: "Frontend" },
  { name: "D3.js",             category: "Frontend" },
  { name: "Three.js",          category: "Frontend" },
  { name: "Framer Motion",     category: "Frontend" },
  { name: "WebGL",             category: "Frontend" },
  { name: "Redux",             category: "Frontend" },
  { name: "Zustand",           category: "Frontend" },
  { name: "Tanstack Query",    category: "Frontend" },
  { name: "Vite",              category: "Frontend" },
  { name: "Webpack",           category: "Frontend" },
  { name: "Storybook",         category: "Frontend" },
  { name: "Lit",               category: "Frontend" },
  { name: "Web Components",    category: "Frontend" },

  // ── Backend ────────────────────────────────────────────────────────────────
  { name: "Node.js",        category: "Backend" },
  { name: "Express",        category: "Backend" },
  { name: "Fastify",        category: "Backend" },
  { name: "NestJS",         category: "Backend" },
  { name: "Django",         category: "Backend" },
  { name: "FastAPI",        category: "Backend" },
  { name: "Flask",          category: "Backend" },
  { name: "Spring Boot",    category: "Backend" },
  { name: "Rails",          category: "Backend" },
  { name: "Laravel",        category: "Backend" },
  { name: "Phoenix",        category: "Backend" },
  { name: "ASP.NET Core",   category: "Backend" },
  { name: "Gin",            category: "Backend" },
  { name: "Echo",           category: "Backend" },
  { name: "Fiber",          category: "Backend" },
  { name: "Hono",           category: "Backend" },
  { name: "Actix",          category: "Backend" },
  { name: "Ktor",           category: "Backend" },
  { name: "Deno",           category: "Backend" },
  { name: "Bun",            category: "Backend" },
  { name: "tRPC",           category: "Backend" },

  // ── Database ───────────────────────────────────────────────────────────────
  { name: "PostgreSQL",   category: "Database" },
  { name: "MySQL",        category: "Database" },
  { name: "SQLite",       category: "Database" },
  { name: "MongoDB",      category: "Database" },
  { name: "Redis",        category: "Database" },
  { name: "Elasticsearch",category: "Database" },
  { name: "DynamoDB",     category: "Database" },
  { name: "Cassandra",    category: "Database" },
  { name: "CockroachDB",  category: "Database" },
  { name: "Neo4j",        category: "Database" },
  { name: "InfluxDB",     category: "Database" },
  { name: "ClickHouse",   category: "Database" },
  { name: "Snowflake",    category: "Database" },
  { name: "BigQuery",     category: "Database" },
  { name: "Firestore",    category: "Database" },
  { name: "Supabase",     category: "Database" },
  { name: "Neon",         category: "Database" },
  { name: "Prisma",       category: "Database" },
  { name: "Drizzle ORM",  category: "Database" },
  { name: "Sequelize",    category: "Database" },
  { name: "TypeORM",      category: "Database" },
  { name: "SQLAlchemy",   category: "Database" },
  { name: "Mongoose",     category: "Database" },
  { name: "Pinecone",     category: "Database" },
  { name: "Weaviate",     category: "Database" },
  { name: "Qdrant",       category: "Database" },

  // ── Cloud ──────────────────────────────────────────────────────────────────
  { name: "AWS",                category: "Cloud" },
  { name: "Google Cloud",       category: "Cloud" },
  { name: "Azure",              category: "Cloud" },
  { name: "Vercel",             category: "Cloud" },
  { name: "Netlify",            category: "Cloud" },
  { name: "Railway",            category: "Cloud" },
  { name: "Fly.io",             category: "Cloud" },
  { name: "DigitalOcean",       category: "Cloud" },
  { name: "Cloudflare",         category: "Cloud" },
  { name: "Cloudflare Workers", category: "Cloud" },
  { name: "Heroku",             category: "Cloud" },
  { name: "Render",             category: "Cloud" },
  { name: "Hetzner",            category: "Cloud" },
  { name: "Oracle Cloud",       category: "Cloud" },

  // ── Infra ──────────────────────────────────────────────────────────────────
  { name: "Docker",          category: "Infra" },
  { name: "Kubernetes",      category: "Infra" },
  { name: "Terraform",       category: "Infra" },
  { name: "Ansible",         category: "Infra" },
  { name: "Helm",            category: "Infra" },
  { name: "Nginx",           category: "Infra" },
  { name: "Traefik",         category: "Infra" },
  { name: "Caddy",           category: "Infra" },
  { name: "Vault",           category: "Infra" },
  { name: "Packer",          category: "Infra" },
  { name: "Pulumi",          category: "Infra" },
  { name: "Nomad",           category: "Infra" },
  { name: "Consul",          category: "Infra" },
  { name: "Prometheus",      category: "Infra" },
  { name: "Grafana",         category: "Infra" },
  { name: "Loki",            category: "Infra" },
  { name: "Istio",           category: "Infra" },

  // ── CI/CD ──────────────────────────────────────────────────────────────────
  { name: "GitHub Actions", category: "CI/CD" },
  { name: "GitLab CI",      category: "CI/CD" },
  { name: "CircleCI",       category: "CI/CD" },
  { name: "Jenkins",        category: "CI/CD" },
  { name: "TeamCity",       category: "CI/CD" },
  { name: "ArgoCD",         category: "CI/CD" },
  { name: "Flux",           category: "CI/CD" },
  { name: "Drone CI",       category: "CI/CD" },
  { name: "Buildkite",      category: "CI/CD" },
  { name: "Travis CI",      category: "CI/CD" },
  { name: "Azure DevOps",   category: "CI/CD" },

  // ── Protocol ───────────────────────────────────────────────────────────────
  { name: "REST API",       category: "Protocol" },
  { name: "GraphQL",        category: "Protocol" },
  { name: "gRPC",           category: "Protocol" },
  { name: "WebSocket",      category: "Protocol" },
  { name: "WebRTC",         category: "Protocol" },
  { name: "MQTT",           category: "Protocol" },
  { name: "SSE",            category: "Protocol" },
  { name: "OAuth 2.0",      category: "Protocol" },
  { name: "OpenID Connect", category: "Protocol" },
  { name: "SOAP",           category: "Protocol" },
  { name: "Webhooks",       category: "Protocol" },

  // ── Messaging ──────────────────────────────────────────────────────────────
  { name: "Kafka",               category: "Messaging" },
  { name: "RabbitMQ",            category: "Messaging" },
  { name: "NATS",                category: "Messaging" },
  { name: "AWS SQS",             category: "Messaging" },
  { name: "AWS SNS",             category: "Messaging" },
  { name: "Redis Pub/Sub",       category: "Messaging" },
  { name: "Apache Pulsar",       category: "Messaging" },
  { name: "EventBridge",         category: "Messaging" },
  { name: "Azure Service Bus",   category: "Messaging" },
  { name: "ActiveMQ",            category: "Messaging" },

  // ── Testing ────────────────────────────────────────────────────────────────
  { name: "Jest",               category: "Testing" },
  { name: "Vitest",             category: "Testing" },
  { name: "Playwright",         category: "Testing" },
  { name: "Cypress",            category: "Testing" },
  { name: "Selenium",           category: "Testing" },
  { name: "pytest",             category: "Testing" },
  { name: "JUnit",              category: "Testing" },
  { name: "Testing Library",    category: "Testing" },
  { name: "k6",                 category: "Testing" },
  { name: "Artillery",          category: "Testing" },
  { name: "Mocha",              category: "Testing" },
  { name: "Chai",               category: "Testing" },
  { name: "Mock Service Worker",category: "Testing" },

  // ── Security ───────────────────────────────────────────────────────────────
  { name: "Auth0",              category: "Security" },
  { name: "Keycloak",           category: "Security" },
  { name: "JWT",                category: "Security" },
  { name: "SSL/TLS",            category: "Security" },
  { name: "AWS IAM",            category: "Security" },
  { name: "Zero Trust",         category: "Security" },
  { name: "OWASP",              category: "Security" },
  { name: "HashiCorp Vault",    category: "Security" },
  { name: "SAST/DAST",          category: "Security" },
  { name: "Penetration Testing",category: "Security" },

  // ── Observability ──────────────────────────────────────────────────────────
  { name: "Datadog",          category: "Observability" },
  { name: "OpenTelemetry",    category: "Observability" },
  { name: "Sentry",           category: "Observability" },
  { name: "New Relic",        category: "Observability" },
  { name: "Splunk",           category: "Observability" },
  { name: "ELK Stack",        category: "Observability" },
  { name: "Honeycomb",        category: "Observability" },
  { name: "Dynatrace",        category: "Observability" },
  { name: "Jaeger",           category: "Observability" },
  { name: "Zipkin",           category: "Observability" },

  // ── Tool ───────────────────────────────────────────────────────────────────
  { name: "Git",           category: "Tool" },
  { name: "GitHub",        category: "Tool" },
  { name: "GitLab",        category: "Tool" },
  { name: "Jira",          category: "Tool" },
  { name: "Linear",        category: "Tool" },
  { name: "Notion",        category: "Tool" },
  { name: "Figma",         category: "Tool" },
  { name: "Postman",       category: "Tool" },
  { name: "Swagger/OpenAPI",category: "Tool" },
  { name: "VS Code",       category: "Tool" },
  { name: "IntelliJ IDEA", category: "Tool" },
  { name: "Vim/Neovim",    category: "Tool" },
  { name: "Turborepo",     category: "Tool" },
  { name: "Nx",            category: "Tool" },
  { name: "pnpm",          category: "Tool" },
  { name: "Stripe API",    category: "Tool" },

  // ── OS ─────────────────────────────────────────────────────────────────────
  { name: "Linux",          category: "OS" },
  { name: "macOS",          category: "OS" },
  { name: "Ubuntu",         category: "OS" },
  { name: "Debian",         category: "OS" },
  { name: "Alpine Linux",   category: "OS" },
  { name: "Windows Server", category: "OS" },

  // ── AI/ML ─────────────────────────────────────────────────────────────────
  { name: "OpenAI API",       category: "AI/ML" },
  { name: "Anthropic API",    category: "AI/ML" },
  { name: "LangChain",        category: "AI/ML" },
  { name: "LangGraph",        category: "AI/ML" },
  { name: "LlamaIndex",       category: "AI/ML" },
  { name: "HuggingFace",      category: "AI/ML" },
  { name: "TensorFlow",       category: "AI/ML" },
  { name: "PyTorch",          category: "AI/ML" },
  { name: "scikit-learn",     category: "AI/ML" },
  { name: "Pandas",           category: "AI/ML" },
  { name: "NumPy",            category: "AI/ML" },
  { name: "Jupyter",          category: "AI/ML" },
  { name: "Ollama",           category: "AI/ML" },
  { name: "RAG",              category: "AI/ML" },

  // ── Architecture ───────────────────────────────────────────────────────────
  { name: "Microservices",             category: "Architecture" },
  { name: "Event-Driven Architecture", category: "Architecture" },
  { name: "Domain-Driven Design",      category: "Architecture" },
  { name: "CQRS",                      category: "Architecture" },
  { name: "Event Sourcing",            category: "Architecture" },
  { name: "Clean Architecture",        category: "Architecture" },
  { name: "Hexagonal Architecture",    category: "Architecture" },
  { name: "API Design",                category: "Architecture" },
  { name: "System Design",             category: "Architecture" },
  { name: "Monorepo",                  category: "Architecture" },

  // ── Product ────────────────────────────────────────────────────────────────
  { name: "A/B Testing",             category: "Product" },
  { name: "Feature Flags",           category: "Product" },
  { name: "Analytics",               category: "Product" },
  { name: "User Research",           category: "Product" },
  { name: "OKRs",                    category: "Product" },
  { name: "Product Thinking",        category: "Product" },
  { name: "Data-Driven Development", category: "Product" },
  { name: "Roadmapping",             category: "Product" },
  { name: "Growth Engineering",      category: "Product" },
  { name: "Experimentation",         category: "Product" },

  // ── Soft Skills ────────────────────────────────────────────────────────────
  { name: "Communication",               category: "Soft Skills" },
  { name: "Leadership",                  category: "Soft Skills" },
  { name: "Mentoring",                   category: "Soft Skills" },
  { name: "Code Review",                 category: "Soft Skills" },
  { name: "Technical Writing",           category: "Soft Skills" },
  { name: "Problem Solving",             category: "Soft Skills" },
  { name: "Critical Thinking",           category: "Soft Skills" },
  { name: "Collaboration",               category: "Soft Skills" },
  { name: "Stakeholder Management",      category: "Soft Skills" },
  { name: "Agile",                       category: "Soft Skills" },
  { name: "Scrum",                       category: "Soft Skills" },
  { name: "Kanban",                      category: "Soft Skills" },
  { name: "Project Management",          category: "Soft Skills" },
  { name: "Public Speaking",             category: "Soft Skills" },
  { name: "Time Management",             category: "Soft Skills" },
  { name: "Conflict Resolution",         category: "Soft Skills" },
  { name: "Cross-functional Collaboration", category: "Soft Skills" },
  { name: "Decision Making",             category: "Soft Skills" },
  { name: "Adaptability",                category: "Soft Skills" },
  { name: "Empathy",                     category: "Soft Skills" },
  { name: "Active Listening",            category: "Soft Skills" },
  { name: "Negotiation",                 category: "Soft Skills" },
  { name: "Presentation Skills",         category: "Soft Skills" },
  { name: "Strategic Thinking",          category: "Soft Skills" },
  { name: "Team Building",               category: "Soft Skills" },
  { name: "Emotional Intelligence",      category: "Soft Skills" },
];

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL! });
const db = drizzle(pool);

await db.insert(techSuggestions).values(SUGGESTIONS).onConflictDoNothing();
await pool.end();
console.log(`Seeded ${SUGGESTIONS.length} tech suggestions.`);
